### ISSUE TITLE
Heimdall Fails To Start - Docker

### ISSUE THREAD

**Issue by kclinden** [mitre/heimdall#41]
## Errror: The page you were looking for doesn't exist.

When trying to run the heimdall app via the docker-compose instructions the web server starts, but the app fails to find /heimdall. 

### Production.log
```
I, [2019-07-30T21:12:59.895232 #1]  INFO -- : [e957aa9e-7c05-41f7-9d36-788d775733e5] Started GET "/heimdall" for 172.18.0.1 at 2019-07-30 21:12:59 +0000
F, [2019-07-30T21:12:59.895947 #1] FATAL -- : [e957aa9e-7c05-41f7-9d36-788d775733e5]   
F, [2019-07-30T21:12:59.895995 #1] FATAL -- : [e957aa9e-7c05-41f7-9d36-788d775733e5] ActionController::RoutingError (No route matches [GET] "/heimdall"):
F, [2019-07-30T21:12:59.896276 #1] FATAL -- : [e957aa9e-7c05-41f7-9d36-788d775733e5]   
F, [2019-07-30T21:12:59.896317 #1] FATAL -- : [e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
[e957aa9e-7c05-41f7-9d36-788d775733e5] vendor/bundle/ruby/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by aaronlippold** [comment]
This is caused by two issues - first 
1. error in readme it should just be localhost:3000/
2. seems our recent rake updates also caused issues: I am seeing this on the db:migrate step
```
➜  heimdall git:(master) docker-compose run web rake db:migrate
Starting heimdall_db_1 ... done
rake aborted!
Gem::LoadError: You have already activated rake 12.3.2, but your Gemfile requires rake 12.3.3. Prepending `bundle exec` to your command may solve this.
/var/www/heimdall/config/boot.rb:3:in `<top (required)>'
/var/www/heimdall/config/application.rb:1:in `require_relative'
/var/www/heimdall/config/application.rb:1:in `<top (required)>'
/var/www/heimdall/Rakefile:4:in `require_relative'
/var/www/heimdall/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)```

**Comment by aaronlippold** [comment]
@kclinden this should be resolved now. Please let us know if you are still having issues.

**Comment by kclinden** [comment]
Got it working. Thanks.
