### ISSUE TITLE
500 error when attempting to load evaluations page

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall#46]
When attempting to navigate to the evaluations page I am receiving the following error:

```
I, [2019-07-31T17:54:07.872120 #1]  INFO -- : [2cc05c3b-f471-4d3f-81d5-c76f370f045d] Completed 500 Internal Server Error in 1305ms (ActiveRecord: 291.8ms)
F, [2019-07-31T17:54:07.872821 #1] FATAL -- : [2cc05c3b-f471-4d3f-81d5-c76f370f045d]   
F, [2019-07-31T17:54:07.872869 #1] FATAL -- : [2cc05c3b-f471-4d3f-81d5-c76f370f045d] NoMethodError (undefined method `>' for nil:NilClass):
F, [2019-07-31T17:54:07.872892 #1] FATAL -- : [2cc05c3b-f471-4d3f-81d5-c76f370f045d]   
F, [2019-07-31T17:54:07.872913 #1] FATAL -- : [2cc05c3b-f471-4d3f-81d5-c76f370f045d] app/controllers/evaluations_controller.rb:23:in `block in index'
[2cc05c3b-f471-4d3f-81d5-c76f370f045d] app/controllers/evaluations_controller.rb:18:in `each'
[2cc05c3b-f471-4d3f-81d5-c76f370f045d] app/controllers/evaluations_controller.rb:18:in `index'
```

I have a large number of historical evaluations that I don't really care about however this happened after migration so I figured I would bring it to your attention.

**Comment by rbclark** [comment]
It seems the fixes that were applied solved the original issue however the page still fails to load with a:

```
D, [2019-08-07T18:59:33.946021 #1] DEBUG -- : [bc786dad-e410-419d-af2e-07c43eb48fdb] get findings
I, [2019-08-07T18:59:33.947180 #1]  INFO -- : [bc786dad-e410-419d-af2e-07c43eb48fdb]   Rendered evaluations/index.html.erb within layouts/application (7.7ms)
I, [2019-08-07T18:59:33.947394 #1]  INFO -- : [bc786dad-e410-419d-af2e-07c43eb48fdb] Completed 500 Internal Server Error in 1237ms (ActiveRecord: 281.5ms)
F, [2019-08-07T18:59:33.947928 #1] FATAL -- : [bc786dad-e410-419d-af2e-07c43eb48fdb]   
F, [2019-08-07T18:59:33.947966 #1] FATAL -- : [bc786dad-e410-419d-af2e-07c43eb48fdb] ActionView::Template::Error (undefined method `controls' for nil:NilClass):
F, [2019-08-07T18:59:33.948110 #1] FATAL -- : [bc786dad-e410-419d-af2e-07c43eb48fdb]     62:                       <td>
[bc786dad-e410-419d-af2e-07c43eb48fdb]     63:                         <table id="message_counts" class="cn-msg-table">
[bc786dad-e410-419d-af2e-07c43eb48fdb]     64:                           <tr>
[bc786dad-e410-419d-af2e-07c43eb48fdb]     65:                             <td><div class="cn-msg-bar bg-green" data-status="0" style="width: <%= pass_pixels(evaluation.findings) %>px"></div></td>
[bc786dad-e410-419d-af2e-07c43eb48fdb]     66:                             <td><div class="cn-msg-bar bg-red" data-status="3" style="width: <%= fail_pixels(evaluation.findings) %>px"></div></td>
[bc786dad-e410-419d-af2e-07c43eb48fdb]     67:                           </tr>
[bc786dad-e410-419d-af2e-07c43eb48fdb]     68:                         </table>
F, [2019-08-07T18:59:33.948136 #1] FATAL -- : [bc786dad-e410-419d-af2e-07c43eb48fdb]   
F, [2019-08-07T18:59:33.948157 #1] FATAL -- : [bc786dad-e410-419d-af2e-07c43eb48fdb] app/models/evaluation.rb:250:in `filtered_controls'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/models/evaluation.rb:134:in `status_counts'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/models/evaluation.rb:20:in `findings'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/views/evaluations/index.html.erb:65:in `block (2 levels) in _app_views_evaluations_index_html_erb___760661607854502086_47119923975760'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/views/evaluations/index.html.erb:53:in `each'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/views/evaluations/index.html.erb:53:in `block in _app_views_evaluations_index_html_erb___760661607854502086_47119923975760'
[bc786dad-e410-419d-af2e-07c43eb48fdb] app/views/evaluations/index.html.erb:35:in `_app_views_evaluations_index_html_erb___760661607854502086_47119923975760'
```

**Comment by rbclark** [comment]
Another layer seems to have popped up on this:

```
D, [2019-08-15T15:10:54.715062 #1] DEBUG -- : [e964437f-f02d-4e43-933e-e154c3558739] get findings
I, [2019-08-15T15:10:54.716586 #1]  INFO -- : [e964437f-f02d-4e43-933e-e154c3558739]   Rendered evaluations/index.html.erb within layouts/application (9.1ms)
I, [2019-08-15T15:10:54.716826 #1]  INFO -- : [e964437f-f02d-4e43-933e-e154c3558739] Completed 500 Internal Server Error in 2319ms (ActiveRecord: 500.3ms)
F, [2019-08-15T15:10:54.717407 #1] FATAL -- : [e964437f-f02d-4e43-933e-e154c3558739]   
F, [2019-08-15T15:10:54.717460 #1] FATAL -- : [e964437f-f02d-4e43-933e-e154c3558739] ActionView::Template::Error (undefined method `includes' for nil:NilClass):
F, [2019-08-15T15:10:54.717626 #1] FATAL -- : [e964437f-f02d-4e43-933e-e154c3558739]     62:                       <td>
[e964437f-f02d-4e43-933e-e154c3558739]     63:                         <table id="message_counts" class="cn-msg-table">
[e964437f-f02d-4e43-933e-e154c3558739]     64:                           <tr>
[e964437f-f02d-4e43-933e-e154c3558739]     65:                             <td><div class="cn-msg-bar bg-green" data-status="0" style="width: <%= pass_pixels(evaluation.findings) %>px"></div></td>
[e964437f-f02d-4e43-933e-e154c3558739]     66:                             <td><div class="cn-msg-bar bg-red" data-status="3" style="width: <%= fail_pixels(evaluation.findings) %>px"></div></td>
[e964437f-f02d-4e43-933e-e154c3558739]     67:                           </tr>
[e964437f-f02d-4e43-933e-e154c3558739]     68:                         </table>
F, [2019-08-15T15:10:54.717658 #1] FATAL -- : [e964437f-f02d-4e43-933e-e154c3558739]   
F, [2019-08-15T15:10:54.717685 #1] FATAL -- : [e964437f-f02d-4e43-933e-e154c3558739] app/models/evaluation.rb:250:in `filtered_controls'
[e964437f-f02d-4e43-933e-e154c3558739] app/models/evaluation.rb:134:in `status_counts'
[e964437f-f02d-4e43-933e-e154c3558739] app/models/evaluation.rb:20:in `findings'
[e964437f-f02d-4e43-933e-e154c3558739] app/views/evaluations/index.html.erb:65:in `block (2 levels) in _app_views_evaluations_index_html_erb__2401828165493949531_47147181450820'
[e964437f-f02d-4e43-933e-e154c3558739] app/views/evaluations/index.html.erb:53:in `each'
[e964437f-f02d-4e43-933e-e154c3558739] app/views/evaluations/index.html.erb:53:in `block in _app_views_evaluations_index_html_erb__2401828165493949531_47147181450820'
[e964437f-f02d-4e43-933e-e154c3558739] app/views/evaluations/index.html.erb:35:in `_app_views_evaluations_index_html_erb__2401828165493949531_47147181450820'
```

**Comment by robthew** [comment]
I can't duplicate or make sense of these errors. Could you send me the evaluations that are breaking so I can debug this problem?

**Comment by rbclark** [comment]
I just cleaned out the database since it wasn't working, I will close this issue for now and send you the files if I manage to recreate it.
