### ISSUE TITLE
Generate PDF for SSP view error

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall#48]
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

**Comment by lukemalinowski** [comment]
Not sure how to check the hatchbox logs, but the development server was able to handle the bad_nginx profile, the rhel-7-output file thats an old linux baseline evaluation.

@ejaronne , when you get a chance can you send me the file which was causing issues?

**Comment by lukemalinowski** [comment]
Could be an issue with sprockets disabled in prod, but if it used to work, then I doubt that is the case.

``` xml
FATAL -- : [37288195-7843-4953-9111-7feffa38e1a6] app/views/layouts/ssp_pdf.html.erb:8:in `_app_views_layouts_ssp_pdf_html_erb__2979509016697837776_702app/models/download.rb:58:in `as_html'
app/models/download.rb:45:in `to_pdf'
app/controllers/downloads_controller.rb:20:in `send_ssp_pdf'
app/controllers/downloads_controller.rb:4:in `block (2 levels) in show'
app/controllers/downloads_controller.rb:3:in `show' 
 INFO -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957] Started GET "/evaluations/9/downloads/9.pdf" for 128.29.43.1 at 2019-08-08 13:00:03 +0000
 INFO -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957] Processing by DownloadsController#show as PDF
 INFO -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957]   Parameters: {"evaluation_id"=>"9", "id"=>"9"}
 
FATAL -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957]
FATAL -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957] ActionView::Template::Error (undefined method `find_asset' for nil:NilClass):
FATAL -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957]      
     5:   <meta name="ROBOTS" content="NOODP" />
     6:   <meta name="viewport" content="initial-scale=1" />
     7:   <style>
     8:     <%= Rails.application.assets.find_asset('ssp_pdf').to_s %>
     9:   </style>
    10: </head>
    11: <body>
FATAL -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957]
FATAL -- : [08ce9e5a-d871-4b18-833d-e8f5706a2957] app/views/layouts/ssp_pdf.html.erb:8:in `_app_views_layouts_ssp_pdf_html_erb__2979509016697837776_702
```
